const { mkdir, writeFile } = require("fs").promises;
const { dirname, resolve } = require("path");

const ENDPOINT =
  "https://atlas.auspic.es/graph/32e9271f-95b6-4541-9f79-50161d595cf9";
const OUTPUT = resolve(__dirname, "../src/generated/content.ts");
const PER_PAGE = 50;

const QUERY = `
  query ContentQuery($page: Int) {
    strata: object {
      ... on Collection {
        contents(page: $page, per: ${PER_PAGE}, sortBy: CREATED_AT_DESC) {
          id
          title: value(key: "title")
          createdAt(relative: true)
          timestamp: createdAt
          metadata
          entity {
            kind: __typename
            ... on Image {
              thumbnail: resized(
                width: 1000
                height: 16
                quality: 75
                sharpen: 1
              ) {
                width
                height
                urls {
                  _1x
                }
              }
              resized(width: 1000, height: 1000, quality: 75) {
                width
                height
                urls {
                  _1x
                }
              }
            }
            ... on Link {
              url
            }
            ... on Text {
              body
            }
          }
        }
      }
    }
  }
`;

const flattenImage = (entity) => {
  if (entity.kind !== "Image") return entity;

  return {
    kind: "Image",
    thumbnail: {
      width: entity.thumbnail.width,
      height: entity.thumbnail.height,
      url: entity.thumbnail.urls._1x,
    },
    resized: {
      width: entity.resized.width,
      height: entity.resized.height,
      url: entity.resized.urls._1x,
    },
  };
};

const fetchPage = async (page) => {
  const response = await fetch(ENDPOINT, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ query: QUERY, variables: { page } }),
  });

  if (!response.ok) {
    throw new Error(`Content request failed: ${response.status}`);
  }

  const { data, errors } = await response.json();

  if (errors?.length) {
    throw new Error(errors[0].message);
  }

  return data.strata.contents.map((content) => ({
    ...content,
    entity: flattenImage(content.entity),
  }));
};

const generate = async () => {
  const contents = [];

  for (let page = 1; ; page++) {
    const next = await fetchPage(page);
    contents.push(...next);

    if (next.length < PER_PAGE) break;
  }

  const source = `// Generated by scripts/generate-content.js. Do not edit.
import { Content } from "../content";

export const CONTENTS: Content[] = ${JSON.stringify(contents)};

export const CONTENTS_BY_ID = new Map(
  CONTENTS.map((content) => [String(content.id), content])
);
`;

  await mkdir(dirname(OUTPUT), { recursive: true });
  await writeFile(OUTPUT, source);
  console.log(`Generated ${contents.length} records.`);
};

generate().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
